meta_product_name: "Wau Wau Club"
meta_title: "Wau Wau Club - Borrow a Four-Legged Friend"
meta_description: "Every dog has his day with Wau Wau Club - play your neighbor's pup at your convenience."
meta_image: "fb_cover.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
