meta_product_name: "Wau Wau Club"
meta_title: "Wau Wau Club - Borrow a dog from time to time"
meta_description: "With Wau Wau Club you can enjoy spending time with a dog - without actually owning one. Just sign up and borrow a nice dog from a friendly owner."
meta_image: "fb_cover.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
